export const LOAD = "LOAD";
export const OPENBOARDMENU = "OPENBOARDMENU";
export const CLOSEMODAL = "CLOSEMODAL";
export const SELECTBOARD = "SELECTBOARD";
export const VIEWTASK = "VIEWTASK";
export const TOGGLESUBTASK = "TOGGLESUBTASK";
export const CHANGESTATUS = "CHANGESTATUS";
